---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - autoconf
      - dpkg-dev
      - file
      - g++
      - gcc
      - libc-dev
      - make
      - pkg-config
      - re2c
      - wget
      - python3-docker
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Setup docker user
  ansible.builtin.user:
    name: docker
    groups: "docker"
    append: true

- name: Add docker user
  user:
    name: "docker"
    groups: sudo
    append: true
    state: present
    createhome: true

- name: Make sudo without password for docker user
  copy:
    dest: /etc/sudoers.d/80-ansible-sudo-user
    content: "docker ALL=(ALL) NOPASSWD:ALL"
    mode: 0440

# - name: Install Docker module for Python
#   ansible.builtin.pip:
#     name: docker


- name: Install Docker-Compose&Set Permission
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: Create Docker-Compose symlink
  ansible.builtin.command:
    cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    creates: /usr/bin/docker-compose

- name: Add private registry
  ansible.builtin.template:
    src: ./files/daemon.j2
    dest: /etc/docker/daemon.json
    mode: preserve

- name: Recursively remove directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true