---
- name: Install gnupg
  apt: pkg=gnupg state=latest update_cache=true

# - name: Add ansible repository
#   ansible.builtin.apt_repository:
#     repo: ppa:ansible/ansible

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: "0644"

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/hashicorp.asc]
      https://apt.releases.hashicorp.com
      {{ ansible_distribution_release }} main
    state: present
    filename: hashicorp

- name: Install ansible&terraform
  ansible.builtin.apt:
    name:
      - ansible
      - terraform
      - git
      - python3
    state: present
    update_cache: true

- name: Clone a github repository
  become_user: iraqez
  ansible.builtin.git:
    repo: https://github.com/iraqez/devops.git
    dest: /home/iraqez/devops/
    clone: yes
    update: yes
    # force: yes

