---
- name: Install gnupg
  apt: pkg=gnupg state=latest update_cache=true

- name: Add ansible repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: add key for terraform
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Add terraform repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com mantic main"
    state: present

- name: Install ansible&terraform
  ansible.builtin.apt:
    name:
      - ansible
      - terraform
      - git
      - python3
      - locales
    state: present
    update_cache: true

- name: Debconf set default locale Ubuntu
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: ru_UA.UTF-8
    vtype: select
  when: ansible_distribution == 'Ubuntu'

- name: set as default locale Ubuntu
  command: localectl set-locale LANG=ru_UA.UTF-8
  when: ansible_distribution == 'Ubuntu'

- name: Clone a github repository
  become_user: iraqez
  ansible.builtin.git:
    repo: https://github.com/iraqez/devops.git
    dest: /home/iraqez/devops/
    clone: yes
    update: yes
    # force: yes





# - name: Generete ssh keys
#   become_user: iraqez
#   openssh_keypair:
#     path: /home/iraqez/.ssh/id_ssh_rsa
